wifi_ssid: "Enter wifi name here"
wifi_password: "Enter wifi password here"

# To create a long lived access key
# Profile > Security > Create Long Lived Token (At the bottom of the security page)
ha_api_key: "Enter HA long lived access token here"
ota_password: "Choose OTA password"
